###
# This setting is used only in development environment
# The infrastructure is already in production but the application need to be make sure
###
version: '3'
services:
  app:
    build: .
    restart: always
    environment:
      APP_ENV: dev
      VARNISH_CONFIG: /etc/varnish/default.vcl
      CACHE_SIZE: 512m
      VARNISHD_PARAMS: -p default_ttl=3600 -p default_grace=3600
      VARNISH_PORT: 80
    volumes:
    - ./uploads:/semarthris/uploads:rw
    links:
    - session
    depends_on:
    - session
  session:
    image: redis:alpine
  balancer:
    image: dockercloud/haproxy:latest
    restart: always
    ports:
    - 8000:80
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - app
    depends_on:
    - app
