php:
    image: comicrelief/php7-slim
    ports:
        - "8080:80"
    volumes:
        - ./:/var/www/html
    links:
        - db
        - redis
db:
    image: mysql:5.7
    ports:
        - "3366:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./mysql_directory:/var/lib/mysql
redis:
    image: redis
    ports:
        - "6379:6379"
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
        - "8888:80"
    links:
        - db
