version: '3'

services:
  web:
    container_name: web
    environment:
      VARNISH_CONFIG: /etc/varnish/default.vcl
      CACHE_SIZE: 512m
      VARNISHD_PARAMS: -p default_ttl=3600 -p default_grace=3600
      VARNISH_PORT: 80
    build:
      context: ./
      dockerfile: docker/dockerfile/web.dockerfile
    restart: always
    ports:
      - "8080:80"
    links:
      - app
  app:
    container_name: app
    build:
      context: ./
      dockerfile: docker/dockerfile/app.dockerfile
    restart: always