apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: slim-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: slim
    servicePort: 80
  rules:
  - host: slim.ilhamarrouf.systems
  - http:
      paths:
      - path: /
        backend:
          serviceName: slim
          servicePort: 80
